export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const UPDATE_USER = "UPDATE_USER";

export const ADD_POST = "ADD_POST";
export const ADD_POST_ERROR = "ADD_POST_ERROR";
export const GET_CURRENT_USER_PROFILE = "GET_CURRENT_USER_PROFILE";
export const GET_OTHER_USER_PROFILE = "GET_OTHER_USER_PROFILE";
export const FOLLOW_UNFOLLOW = "FOLLOW_UNFOLLOW"
export const PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND";
export const SET_LOADING = "SET_LOADING";
export const CLEAR_STATE = "CLEAR_STATE";
